import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Resume Analyzer",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 p-4">
      <h1 className="text-2xl font-bold mb-4">AI Resume Analyzer</h1>

      <Link
        href="/resume-analysis"
        className="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-700"
      >
        View Analysis
      </Link>
    </div>
  );
}
